name: Build and release with gradle

on:
  push:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build
      
    - name: Get version
      run: |
       grep ^version: app/src/main/resources/plugin.yml >> $GITHUB_ENV

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.version }}
        artifacts: "app/build/libs/app.jar,app/build/resources/main/plugin.yml"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.TOKEN_PCIPLUGIN_RELEASE }}
