# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and release

on:
  push:
    branches: [ production ]
    tags:
    - 'release'
  pull_request:
    branches: [ production ]
    tags:
    - 'release'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/libs/app.jar"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
